// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukftlivoujhgrqnxgrhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZnRsaXZvdWpoZ3JxbnhncmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDQwMDcsImV4cCI6MjA2MzY4MDAwN30.Yp5mIexSmeozvFe4oNeYl_YikQLiprisbhtgpZ-4Xxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);